/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './src/app/index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1b1c1c',
        'surface-container': '#1f2020',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'on-surface': '#e4e2e1',
        'on-surface-variant': '#c0cab5',
        'inverse-surface': '#e4e2e1',
        'inverse-on-surface': '#303030',
        outline: '#8a9481',
        'outline-variant': '#41493a',
        'surface-tint': '#89db60',
        primary: '#93e569',
        'on-primary': '#113800',
        'primary-container': '#78c850',
        'on-primary-container': '#1c5100',
        'inverse-primary': '#286c00',
        secondary: '#82cfff',
        'on-secondary': '#00344b',
        'secondary-container': '#00abec',
        'on-secondary-container': '#003c55',
        tertiary: '#ffc1b8',
        'on-tertiary': '#690100',
        'tertiary-container': '#ff9989',
        'on-tertiary-container': '#920100',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#a4f879',
        'primary-fixed-dim': '#89db60',
        'on-primary-fixed': '#072100',
        'on-primary-fixed-variant': '#1c5200',
        'secondary-fixed': '#c6e7ff',
        'secondary-fixed-dim': '#82cfff',
        'on-secondary-fixed': '#001e2d',
        'on-secondary-fixed-variant': '#004c6b',
        'tertiary-fixed': '#ffdad4',
        'tertiary-fixed-dim': '#ffb4a8',
        'on-tertiary-fixed': '#410000',
        'on-tertiary-fixed-variant': '#930100',
        background: '#131313',
        'on-background': '#e4e2e1',
        'surface-variant': '#353535',
      },
      fontFamily: {
        headline: ['Space Mono', 'monospace'],
        body: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-1px' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'label-lg': ['12px', { lineHeight: '1.0', fontWeight: '700' }],
        'label-sm': ['10px', { lineHeight: '1.0', fontWeight: '700' }],
      },
      spacing: {
        unit: '4px',
        gutter: '16px',
        'margin-mobile': '12px',
        'margin-desktop': '32px',
      },
      borderWidth: {
        DEFAULT: '3px',
      },
    },
  },
  plugins: [],
};